title: 93Hong Blog
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://93hong.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: https://github.com/93Hong
   linkedin: 93Hong
   email: sk2rldnr@gmail.com

google_analytics: "UA-58263416-1"
